name: Build Kivy AAB

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: kivy/buildozer:latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Force non-interactive mode
      run: |
        export BUILDOZER_ALLOW_ROOT=1
        export CI=1

    - name: Build AAB (no prompts)
      run: |
        buildozer -v android release --ignore-root-warning

    - name: Upload AAB
      uses: actions/upload-artifact@v4
      with:
        name: snake-aab
        path: bin/*.aab
